const { GoogleGenAI } = require('@google/genai');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const { marked } = require('marked');
const { chromium } = require('playwright');
const driveService = require('../../src/services/drive-service');
const { isAuthenticated } = require('../../src/auth/google-auth');
const { withMemoryApiKey } = require('../../src/knowledge/memory-api-key');

async function generatePdfReport(htmlContent, claim, sdk) {
    sdk.reportProgress(85, 'Rendering Truth-O-Meter report layout...');
    const safeClaim = claim.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 40);
    const pdfPath = path.join(os.tmpdir(), `FactCheck_${safeClaim}.pdf`);

    const fullHtml = `
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 40px; background-color: #fafafa; }
                .container { background: #fff; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); }
                h1 { color: #1a1a1a; margin-top: 0; padding-bottom: 15px; border-bottom: 2px solid #eaeaea; text-align: center; font-size: 28px; }
                h2 { color: #2c3e50; margin-top: 1.5em; border-bottom: 1px solid #eee; padding-bottom: 5px; }
                p { margin-bottom: 1.2em; font-size: 16px; }
                ul, ol { font-size: 16px; padding-left: 20px; }
                li { margin-bottom: 8px; }
                a { color: #0366d6; text-decoration: none; word-break: break-all; }
                .truth-meter { text-align: center; margin: 30px 0; padding: 20px; border-radius: 8px; font-weight: bold; font-size: 24px; text-transform: uppercase; letter-spacing: 2px; color: #fff; }
                /* Gemini will output specific truth labels, we can style them generally or rely on inline styles. Gemini will just output standard markdown which marked parses, so we add some global styling to make markdown look good. */
                blockquote { border-left: 4px solid #005A9C; background-color: #f0f7fb; color: #2c3e50; padding: 15px; margin-left: 0; border-radius: 0 8px 8px 0; font-style: italic; }
                .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 20px; }
            </style>
        </head>
        <body>
            <div class="container">
                ${htmlContent}
                <div class="footer">
                    Generated by Summer Fact Checker (Powered by Google Gemini)<br>
                    Date: ${new Date().toLocaleDateString()}
                </div>
            </div>
        </body>
        </html>
    `;

    sdk.reportProgress(90, 'Launching PDF renderer...');
    const browser = await chromium.launch();
    try {
        const page = await browser.newPage();
        sdk.reportProgress(94, 'Rendering Fact Check Document...');
        await page.setContent(fullHtml, { waitUntil: 'domcontentloaded' });
        
        sdk.reportProgress(97, 'Generating PDF pages...');
        await page.pdf({ 
            path: pdfPath, 
            format: 'A4', 
            margin: { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' },
            printBackground: true
        });
        sdk.reportProgress(98, 'PDF report generated successfully.');
    } finally {
        await browser.close();
    }
    
    return pdfPath;
}

async function main(taskManifest, sdk) {
    try {
        const { claim, context = '' } = taskManifest;

        sdk.reportProgress(10, `Initializing Fact Checker for claim...`);
        sdk.reportProgress(20, 'Cross-referencing claim across web sources...');

        const prompt = `
        You are an expert fact-checker and investigative journalist.
        Please thoroughly fact-check the following claim using Google Search:
        CLAIM: "${claim}"
        CONTEXT (if any): "${context}"

        Your output must be a well-structured markdown document.
        Please structure your report as follows:
        # Fact Check Report

        ## The Claim
        > "${claim}"

        ## Verdict
        Provide a clear "Truth-O-Meter" style verdict (e.g., TRUE, MOSTLY TRUE, HALF TRUE, MOSTLY FALSE, FALSE, PANTS ON FIRE). 
        You MUST wrap the verdict in an HTML block with an appropriate background color so it stands out vividly in the report. For example:
        <div style="background-color: #e74c3c; color: white; padding: 15px; text-align: center; font-size: 24px; font-weight: bold; border-radius: 8px;">VERDICT: FALSE</div>

        ## Confidence Score
        Provide a confidence score out of 100% based on the quality and consensus of the sources.

        ## Detailed Analysis
        Explain why this verdict was reached. Break down the nuances, address any kernels of truth, and explain where the claim diverges from reality.

        ## Citations & Sources
        Provide a bulleted list of the most reputable sources you found that verify or debunk this claim. Include URLs.
        `;

        sdk.reportProgress(40, 'Evaluating source credibility and analyzing data...');

        const markdownRaw = await withMemoryApiKey(async (apiKey) => {
            const client = new GoogleGenAI({ apiKey });
            const response = await client.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: prompt,
                config: {
                    tools: [{ googleSearch: {} }]
                }
            });
            return response.text;
        }, { caller: 'FactChecker' });

        sdk.reportProgress(70, 'Calculating confidence score and formatting report...');

        const htmlContent = marked.parse(markdownRaw);
        const docPath = await generatePdfReport(htmlContent, claim, sdk);
        
        // Upload to Google Drive if authenticated
        if (await isAuthenticated()) {
            sdk.reportProgress(99, 'Uploading report to Google Drive...');
            const driveResult = await driveService.uploadFile(docPath, 'application/pdf', true);
            sdk.complete({ 
                message: `The Fact Check report for the claim is ready. It has been saved to your Google Drive.`,
                file_path: docPath,
                drive_url: driveResult.url 
            });
        } else {
            sdk.complete({ 
                message: "The Fact Check report is ready and saved locally.",
                file_path: docPath 
            });
        }

    } catch (error) {
        console.error('Fact Checker Agent failed:', error);
        sdk.fail({ error: error.message });
    }
}

module.exports = { main };
