const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('memoryAPI', {
    uploadFiles: (files) => ipcRenderer.invoke('upload-files', files),
    getGraph: () => ipcRenderer.invoke('get-graph'),
    clearGraph: () => ipcRenderer.invoke('clear-graph'),
    updateNode: (nodeId, updates) => ipcRenderer.invoke('update-node', nodeId, updates),
    deleteNode: (nodeId) => ipcRenderer.invoke('delete-node', nodeId),
    addTag: (nodeId, tag) => ipcRenderer.invoke('add-tag', nodeId, tag),
    removeTag: (nodeId, tag) => ipcRenderer.invoke('remove-tag', nodeId, tag),
    getTags: () => ipcRenderer.invoke('get-tags'),
    getDiary: () => ipcRenderer.invoke('get-diary'),
    pinNode: (nodeId, pinned) => ipcRenderer.invoke('pin-node', nodeId, pinned),
    setImportance: (nodeId, importance) => ipcRenderer.invoke('set-importance', nodeId, importance),
    addEdge: (fromId, toId, label) => ipcRenderer.invoke('add-edge', fromId, toId, label),
    optimizeGraph: () => ipcRenderer.invoke('optimize-graph'),
    runMemoryCommand: (cmd) => ipcRenderer.invoke('run-memory-command', cmd),
    revertGraph: () => ipcRenderer.invoke('revert-graph'),
    checkBackup: () => ipcRenderer.invoke('check-backup'),
    exportMemory: () => ipcRenderer.invoke('export-memory'),
    importMemory: () => ipcRenderer.invoke('import-memory'),
    ingestUrl: (url) => ipcRenderer.invoke('ingest-url', url),
    onExtractionProgress: (callback) => ipcRenderer.on('extraction-progress', (_, msg) => callback(msg)),
    onExtractionDone: (callback) => ipcRenderer.on('extraction-done', (_, graph) => callback(graph)),
    onExtractionError: (callback) => ipcRenderer.on('extraction-error', (_, err) => callback(err)),
    onMemoryConflict: (callback) => ipcRenderer.on('memory-conflict', (_, conflicts) => callback(conflicts)),
    resolveConflict: (resolution) => ipcRenderer.invoke('resolve-conflict', resolution),
    readLocalImage: (filename) => ipcRenderer.invoke('read-local-image', filename),
    readLocalAudio: (filename) => ipcRenderer.invoke('read-local-audio', filename),
    getTimeline: (options) => ipcRenderer.invoke('get-timeline', options),
    getTimelineStats: () => ipcRenderer.invoke('get-timeline-stats'),
});
